### ISSUE TITLE
Refactorizar estilos en `src/pages` para eliminar dependencia de `html.dark` y usar variables CSS para el tema oscuro

### ISSUE THREAD

**Issue by beresiartejuan** [CROBF-ARG/website#34]
**Descripción:**  
Actualmente, el cambio entre el modo claro y oscuro se maneja agregando o quitando la clase `dark` en la etiqueta `<html>`, y los estilos específicos para el modo oscuro se definen usando selectores como `html.dark`. Sin embargo, vamos a migrar a un sistema donde el cambio de tema se manejará directamente modificando las variables CSS, eliminando la necesidad de usar la clase `dark`.

El objetivo de esta tarea es refactorizar los archivos dentro de la carpeta `src/pages` para eliminar todos los bloques de estilos que comienzan con `html.dark` y asegurarnos de que los estilos usen únicamente variables CSS. Por ejemplo:

**Antes:**
```css
.motto {
    color: var(--accent);
    font-size: 30px;
}
html.dark .motto {
    color: #a8a8ff;
}
```

**Después:**
```css
.motto {
    color: var(--accent);
    font-size: 30px;
}
```

**Instrucciones:**  
1. A partir del **11 de marzo**, revisa todos los archivos dentro de la carpeta `src/pages` que contengan estilos CSS.  
2. Elimina todos los bloques de estilos que comiencen con `html.dark`.  
3. Asegúrate de que los estilos que dependían de `html.dark` ahora usen variables CSS para manejar los cambios de tema.  
4. Verifica que los cambios no afecten negativamente la apariencia de la aplicación en modo claro u oscuro.  
5. Si encuentras estilos que no pueden ser reemplazados directamente con variables CSS, notifícalo para revisión.  

**Notas adicionales:**  
- No hay una fecha límite para esta tarea, pero se espera que se realice de manera consistente y sin prisa.  
- Asegúrate de que las variables CSS estén correctamente definidas en el sistema antes de eliminar los bloques `html.dark`.  
- Si tienes dudas sobre cómo manejar algún caso específico, no dudes en preguntar.  
- Trabajar sobre la rama "refactor-css-styles"

**Ejemplo de archivo modificado:**  
```css
/* Antes */
.motto {
    color: var(--accent);
    font-size: 30px;
}
html.dark .motto {
    color: #a8a8ff;
}

/* Después */
.motto {
    color: var(--accent);
    font-size: 30px;
}
```

**Prioridad:**  
Media
